services:
  postgres:
    container_name: devboard-db
    image: postgres:16-alpine

    ports:
      - "${POSTGRES_HOST_PORT}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d:ro

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: unless-stopped

  backend:
    container_name: devboard-backend
    image: "${DOCKERHUB_USERNAME}/devboard-backend:ci-v2"

    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_PORT}"

    environment:
      PORT: "${BACKEND_PORT}"
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

  frontend:
    container_name: devboard-frontend
    image: "${DOCKERHUB_USERNAME}/devboard-frontend:ci-v2"

    ports:
      - "${FRONTEND_HOST_PORT}:4173"

    depends_on:
      - backend

    restart: unless-stopped

volumes:
  pgdata: